name: ci

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        node: ["*", "16", "14"]
    runs-on: ${{ matrix.os }}-latest
    name: ${{ matrix.os }} node@${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          check-latest: ${{ matrix.node == '*' }}
      - name: Install
        run: npm install
      - name: Start docker
        if: matrix.os == 'macos'
        run: brew install docker docker-compose && colima start
      - name: Start containers
        run: docker-compose up -d
      - name: Sleep for 5s
        if: matrix.os != 'macos'
        run: sleep 5s;
      - name: Sleep for 5s
        if: matrix.os == 'macos'
        run: sleep 5;
      - name: test
        run: npm test
