name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        node: ['*', '14', '12']
        hapi: ['20', '19']

    runs-on: ${{ matrix.os }}-latest
    name: ${{ matrix.os }} node@${{ matrix.node }} hapi@${{ matrix.hapi }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        run: npm install
      - name: Install hapi
        run: npm install @hapi/hapi@${{ matrix.hapi }}
      - name: Install docker
        if: matrix.os == 'macos'
        uses: docker-practice/actions-setup-docker@v1
      - name: Start containers
        run: docker-compose up -d
      - name: Sleep for 5s
        run: sleep 5s;
      - name: test
        run: npm test
